version: '3.2'

services:
  producer:
    build:
      context: ../rabbitmq-example-producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal

  worker:
    build:
      context: ../rabbitmq-example-worker
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - internal

  audit:
    build:
      context: ../rabbitmq-example-audit
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - internal

networks:
  internal: